### ISSUE TITLE
请问您布置DOCKER版本的具体参数是什么

### ISSUE THREAD

**Issue by yizhuce** [primovist/BaiduNetDisk-docker#1]
没有部署成功。想请教具体的参数

**Comment by primovist** [comment]
这个是我自己在电脑上做的image，设置如下。
[cid:FBBCF8C3-211E-46E4-910C-0B2C70F79FE0-L0-001][cid:D5F7824B-1840-4B29-9352-8994234BF56B-L0-001]

发自我的iPhone

在 2021年4月5日，21:26，Ustoppable ***@***.***> 写道：

﻿

没有部署成功。想请教具体的参数

**Comment by yizhuce** [comment]
谢谢您的解答。我试试看
